name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "iliasmachairas@outlook.com"
          git config --global user.name "iliasmachairas"

      - name: Clone destination repository
        run: |
          git clone https://${{ secrets.PAT }}@github.com/iliasmachairas/sync_project.git
          cd sync_project
          git remote add source https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git
          git fetch source
          git checkout -b temp-branch source/main
          git checkout main
          git merge temp-branch
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: iliasmachairas
